name: Tests

on:
  push:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/prepare-host

      - uses: ./.github/actions/build
      
      - uses: ./.github/actions/run-tests